### PR TITLE
flow: add unit test for yaw motion

### PR DESCRIPTION
**Pull request by bresch**
Because unit tests are fun!

### CODE REVIEW

**Review by kamilritz — DISMISSED** [review]
It is fun, especially if you find the code not working as expected.
Looks good in general. Added some suggestions. How sure are you about the placement of a minus or plus sign in front of the computed body_rate?

**Comment by bresch** [comment]
Thanks @kamilritz for the review. I addressed your comments.

> especially if you find the code not working as expected

Yes, I actually started that because the drone is never really locked-in when yawing in opt flow fusion only. So probably the issue is not on the EKF side, but due to the sensor.

> How sure are you about the placement of a minus or plus sign in front of the computed body_rate?

Really sure: https://github.com/PX4/PX4-ECL/blob/df7f261e038aa80b07a91857f2f952280938bfc6/EKF/common.h#L139
Rotation of the image = - rotation of the body
See also in https://github.com/PX4/PX4-ECL/blob/df7f261e038aa80b07a91857f2f952280938bfc6/EKF/optflow_fusion.cpp#L363

**Comment by kamilritz** [comment]
@bresch  I do not see any update to the PR. If this is intentional, please go ahead and merge it.

**Comment by bresch** [comment]
@kamilritz I forgot to push... :|

**Review by kamilritz — APPROVED** [review]
Thought so. Looks good to me.

**Pull request merged**
